// laravel-vue/vue-app/src/components/Card.vue
<template>
    <article class='relative rounded-md shadow-md bg-stone-50'>
        <div style="backgroundColor: #333;" 
        class="p-4 text-custom-gray2 rounded-md absolute inset-0 z-10 transition-opacity duration-500"
        :class="isFlipped ? 'opacity-95' : 'opacity-0 pointer-events-none'"
        >
            <ul>
                <li>
                    allergies...
                </li>
            </ul>
        </div>
        <div class='relative rounded-t-md overflow-hidden'>
            <img class='duration-500 transition-transform hover:scale-125 w-full h-64 object-cover' :src="image" alt="Exemple carta"/>
            <infoCircle @click="isFlipped = !isFlipped" class='absolute top-1.5 right-1.5 z-20 text-primary'/>
        </div>
        <div class='p-4 flex flex-col gap-1'>
            <div class='flex justify-between'>
                <p class='font-bold'>
                    {{name}}
                </p>
                <p class='font-bold'>
                    {{price}}€
                </p>
            </div>
            <p class="mb-4">
                {{description}}
            </p>
            <customButton :asWhite="false" text="Afegir" />
        </div>
    </article>
</template>

<script>
import infoCircle from "@/components/icons/infoCircle.vue";
import customButton from "@/components/customButton.vue";

export default {
    props: {
        id: Number, 
        image: String, 
        name: String, 
        price: Number, 
        description: String, 
        allergies: Array,
    },
    components: {
        infoCircle,
        customButton,
    },
    data() {
        return {
            isFlipped: false,
        };
    },
};
</script>

// next-upc-iu/app/components/card.jsx
'use client'

import Image from 'next/image'
import { FaInfoCircle } from 'react-icons/fa'
import Button from '../components/button'
import { useState } from 'react'

function Card({image, name, price, description, data}) {

  const [isFlipped, setFlipped] = useState(false);

  const toggleCard = () => {
    setFlipped(!isFlipped);
  };

  return ( 
    <article className='relative rounded-md shadow-md bg-stone-50'>
      <div style={{ backgroundColor: "#333" }} className={`p-4 text-custom-gray2 rounded-md absolute inset-0 z-10 transition-opacity duration-500 ${isFlipped ? 'opacity-95' : 'opacity-0 pointer-events-none'}`}>
        <ul>
          <li>
            Al·lergògen 1
          </li>
          <li>
            Al·lergògen 2
          </li>
          <li>
            Al·lergògen 3
          </li>
        </ul>
      </div>
      <div className='relative rounded-t-md overflow-hidden'>
        <Image className='duration-500 transition-transform hover:scale-125' src={image} alt="Exemple carta" width={500} height={500}/>
        <FaInfoCircle onClick={toggleCard} size={20} className='absolute top-1.5 right-1.5 z-20 text-stone-50'/>
      </div>
      <div className='p-4 flex flex-col gap-1'>
        <div className='flex justify-between'>
          <p className='font-bold'>
            {name}
          </p>
          <p className='font-bold'>
            {price}€
          </p>
        </div>
        <p className="mb-4">
          {description}
        </p>
        <Button text="Afegir" />
      </div>
    </article>
  );
}

export default Card;
