// next-upc-iu/app/components/genericdropdown.jsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import {MdOutlineArrowDropDown} from 'react-icons/md'
import { useState } from 'react';
import { signOut } from 'next-auth/react';
import { CiMenuBurger } from 'react-icons/ci';

export default function GenericDropdown() {

  const [genericDropdown, setGenericDropdown] = useState(false);

  const handleGenericDropdown = () => {
    setGenericDropdown(!genericDropdown);
  }

  return (
    <div className="relative">
      <CiMenuBurger size={30} className="md:hidden cursor-pointer hover:text-primary" onClick={handleGenericDropdown}/>
      <div 
      className={`absolute top-[120%] md:hidden flex flex-col gap-2 w-fit left-[50%] translate-x-[-50%] p-4 bg-white rounded shadow-md border right-0 z-30 transition-all duration-250 ${genericDropdown ? 'visible opacity-100' : 'invisible opacity-0'}`}>
        <Link href="/reserva" className="w-full uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
          Reservar taula
        </Link>
        <Link href="/carta" className="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
          Carta
        </Link>
      </div>
    </div>
  );
}

// laravel-vue/vue-app/src/components/genericDropdown.vue
<template>
    <div class="relative">
        <menuBurger class="md:hidden cursor-pointer hover:text-primary" @click="genericDropdown = !genericDropdown" />
        <div 
        class="absolute top-[120%] md:hidden flex flex-col gap-2 w-fit left-[50%] translate-x-[-50%] p-4 bg-white rounded shadow-md border right-0 z-30 transition-all duration-250"
        :class="genericDropdown ? 'visible opacity-100' : 'invisible opacity-0'">
            <a href="#" class="w-full uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
                Reservar taula
            </a>
            <router-link to="/carta" class="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
                Carta
            </router-link>
        </div>
    </div>
</template>

<script>
import menuBurger from "@/components/icons/menuBurger.vue";

export default {
    components: {
        menuBurger,
    },
    data() {
        return {
            genericDropdown: false,
        };
    },
};
</script>
