// laravel-vue/vue-app/src/components/loginDropdown.vue
<template>
    <div class='relative'>
        <div>
            <div class='hidden md:flex items-center gap-2'>
                <img class='rounded-full w-[32px]' :src="imgUrl" alt="img de perfil" />
                <div @click="loginDropdown = !loginDropdown" class='flex cursor-pointer hover:text-primary'>
                    <p class='font-medium select-none'>
                        {{name}}
                    </p>
                    <arrowDropdown />
                </div>
            </div>
            <img @click="loginDropdown = !loginDropdown" class='md:hidden rounded-full w-[32px] cursor-pointer' :src="imgUrl" alt="img usuari" />
        </div>

        <div 
            class="absolute w-fit p-2 bg-white rounded shadow-md border right-0 mt-[12px] z-30 transition-all duration-250"
            :class="loginDropdown ? 'visible opacity-100' : 'invisible opacity-0'"
            >
            <ul class='text-sm text-gray-700 flex flex-col gap-2 list-none'>
                <li>
                    <a href='#' class="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
                        Perfil
                    </a>
                </li>
                <li>
                    <a href='#' class="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap" onClick={handleLogOut}>
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</template>

<script>
import arrowDropdown from "@/components/icons/arrowDropdown.vue";

export default {
    components: {
        arrowDropdown,
    },
    props: {
        name: String,
        imgUrl: String,
    },
    data() {
        return {
            loginDropdown: false,
        };
    },
};
</script>

// next-upc-iu/app/[lng]/components/logindropdown.jsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import {MdOutlineArrowDropDown} from 'react-icons/md'
import { useState } from 'react';
import { signOut } from 'next-auth/react'
import { useTranslation } from "@/app/i18n/client";

export default function LoginDropdown({name, imageUrl, lng}) {
  const { t } = useTranslation(lng)
  const [stateDropdown, setDropdown] = useState(false);

  const handleDropdown = () => {
    setDropdown(!stateDropdown);
  }

  const handleLogOut = () => {
    signOut('google');
  }

  return (
    <div className='relative'>
      <div>
        <div className='hidden md:flex items-center gap-2'>
          <Image className='rounded-full' src={imageUrl} alt="Imagen de perfil" width={32} height={32} />
          <div onClick={handleDropdown}  className='flex cursor-pointer hover:text-primary'>
            <p className='font-medium select-none'>
              {name}
            </p>
            <MdOutlineArrowDropDown size={24} />
          </div>
        </div>
        <Image onClick={handleDropdown} className='md:hidden rounded-full cursor-pointer' src={imageUrl} alt="Imagen de perfil" width={32} height={32} />
      </div>

      <div className={`absolute w-fit p-2 bg-white rounded shadow-md border right-0 mt-[12px] z-30 transition-all duration-250 ${stateDropdown ? 'visible opacity-100' : 'invisible opacity-0'}`}>
        <ul className='text-sm text-gray-700 flex flex-col gap-2 list-none'>
          <li>
            <Link href='#' className="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap">
              {t('header_profile')}
            </Link>
          </li>
          <li>
            <a href='#' className="uppercase text-lg transition-colors hover:text-primary whitespace-nowrap" onClick={handleLogOut}>
              {t('header_logout')}
            </a>
          </li>
        </ul>
      </div>
    </div>
  );
}
